protocol/src/main/protos/api/api.proto
testcase/src/test/java/stest/tron/wallet/dailybuild/manual/WalletTestBlock003.java

Add getBlock Api case
4.5.2 API must be test 100%
- Unit Tests
**Follow up**

Add getBlock Api case

---

testcase/src/test/java/stest/tron/wallet/dailybuild/manual/WalletTestBlock003.java

Modify getblock testcase

---

testcase/src/test/java/stest/tron/wallet/dailybuild/jsonrpc/Accounts002.java
testcase/src/test/java/stest/tron/wallet/dailybuild/jsonrpc/EthSmartContract001.java

Modify jsonrpc eth_call and eth_EstimateGas api test

---

testcase/src/test/java/stest/tron/wallet/dailybuild/manual/WalletTestBlock003.java

Release_v4.5.2 add getBlock api, daily build should be test it.
Daily build test case must be passed 100%.
- Unit Tests
**Follow up**

Add getblock api test case

---

testcase/src/test/java/stest/tron/wallet/common/client/utils/HttpMethed.java
testcase/src/test/java/stest/tron/wallet/common/client/utils/JsonRpcBase.java
testcase/src/test/java/stest/tron/wallet/dailybuild/eventquery/EventQuery001.java
testcase/src/test/java/stest/tron/wallet/dailybuild/eventquery/mongoevent/MongoEventQuery001.java
testcase/src/test/java/stest/tron/wallet/dailybuild/eventquery/mongoevent/MongoEventQuery002.java
testcase/src/test/java/stest/tron/wallet/dailybuild/eventquery/mongoevent/MongoEventQuery003.java
testcase/src/test/java/stest/tron/wallet/dailybuild/eventquery/mongoevent/MongoEventQuery004.java
testcase/src/test/java/stest/tron/wallet/dailybuild/http/HttpTestBlock001.java
testcase/src/test/java/stest/tron/wallet/dailybuild/http/HttpTestGetAccountBalance001.java
testcase/src/test/java/stest/tron/wallet/dailybuild/jsonrpc/Accounts001.java
testcase/src/test/java/stest/tron/wallet/dailybuild/jsonrpc/Accounts002.java
testcase/src/test/java/stest/tron/wallet/dailybuild/jsonrpc/Accounts003.java
testcase/src/test/java/stest/tron/wallet/dailybuild/jsonrpc/Accounts004.java
testcase/src/test/java/stest/tron/wallet/dailybuild/jsonrpc/GetBlock001.java

Release_v4.5.2 add http GetBlock api
Daily build must coverage 100% api test
- Unit Tests
**Follow up**

Add getblock api

---

testcase/src/test/java/stest/tron/wallet/dailybuild/eventquery/mongoevent/MongoEventQuery002.java
testcase/src/test/java/stest/tron/wallet/dailybuild/http/HttpTestGetAccountBalance001.java

Fix test case bug
Daily build must be passed 100%
- Unit Tests
**Follow up**

Fix test case issue

---

testcase/src/test/java/stest/tron/wallet/dailybuild/jsonrpc/Accounts001.java
testcase/src/test/java/stest/tron/wallet/dailybuild/jsonrpc/Accounts002.java

Fix connect to infura failed issue
JSON-PRC api web3sha3 should be pass.
- Unit Tests
**Follow up**

Remove web3sha3 api to eth

---

testcase/src/test/java/stest/tron/wallet/dailybuild/jsonrpc/Accounts001.java
testcase/src/test/java/stest/tron/wallet/dailybuild/jsonrpc/Accounts002.java

Fix web3_sha3 api test failed
Daily build must be passed 100%
- Unit Tests
**Follow up**

Fix web3_sha3 api test failed

---

testcase/src/test/java/stest/tron/wallet/onlinestress/CreateReplayTestUsedAccount.java

Use to test stress test
Daily build task need.
- Unit Tests
**Follow up**

Add muti account with muti trc10/trc20 test case

---

testcase/src/test/java/stest/tron/wallet/common/client/utils/PublicMethed.java
testcase/src/test/java/stest/tron/wallet/common/client/utils/PublicMethedForMutiSign.java
testcase/src/test/java/stest/tron/wallet/dailybuild/assetissue/exchangeandtoken/WalletTestAssetIssue018.java
testcase/src/test/java/stest/tron/wallet/dailybuild/eventquery/mongoevent/MongoEventQuery002.java
testcase/src/test/java/stest/tron/wallet/dailybuild/operationupdate/MutiSignSmartContractTest.java
testcase/src/test/java/stest/tron/wallet/dailybuild/trctoken/ContractTrcToken039.java
testcase/src/test/java/stest/tron/wallet/dailybuild/tvmnewcommand/tvmFreeze/FreezeContractTest001.java
testcase/src/test/java/stest/tron/wallet/dailybuild/tvmnewcommand/tvmFreeze/FreezeContractTest002.java

Fix instable cases

---

testcase/src/test/java/stest/tron/wallet/dailybuild/operationupdate/MutiSignSmartContractTest.java

fix unstable case

---

testcase/src/test/java/stest/tron/wallet/dailybuild/manual/WalletTestAccount014.java

Fix issue of WalletTestAccount014

---

testcase/src/test/java/stest/tron/wallet/common/client/utils/PublicMethed.java

Fix getWitnessNum func

---

protocol/src/main/protos/api/api.proto
testcase/src/test/java/stest/tron/wallet/common/client/utils/HttpMethed.java
testcase/src/test/java/stest/tron/wallet/common/client/utils/PublicMethed.java
testcase/src/test/java/stest/tron/wallet/dailybuild/freezeV2/DelegateResourceV2TimestampTest.java
testcase/src/test/java/stest/tron/wallet/dailybuild/freezeV2/FreezeBalanceV2Test001.java
testcase/src/test/java/stest/tron/wallet/dailybuild/freezeV2/FreezeBalanceV2Test002.java
testcase/src/test/java/stest/tron/wallet/dailybuild/freezeV2/FreezeBalanceV2Test004.java
testcase/src/test/java/stest/tron/wallet/dailybuild/freezeV2/FreezeBalanceV2Test006.java
testcase/src/test/java/stest/tron/wallet/dailybuild/http/HttpTestFreezeV2001.java

add FreezeV2 HTTP&GRPC query interface cases for fullnode and solidity node
- Unit Tests
**Follow up**

add FreezeV2 HTTP query interface for fullnode and solidity node

---

testcase/src/test/java/stest/tron/wallet/common/client/utils/HttpMethed.java
testcase/src/test/java/stest/tron/wallet/dailybuild/freezeV2/DelegateResourceV2TimestampTest.java
testcase/src/test/java/stest/tron/wallet/dailybuild/freezeV2/FreezeBalanceV2Test001.java
testcase/src/test/java/stest/tron/wallet/dailybuild/freezeV2/FreezeBalanceV2Test002.java
testcase/src/test/java/stest/tron/wallet/dailybuild/freezeV2/FreezeBalanceV2Test003.java
testcase/src/test/java/stest/tron/wallet/dailybuild/freezeV2/FreezeBalanceV2Test004.java
testcase/src/test/java/stest/tron/wallet/dailybuild/freezeV2/FreezeBalanceV2Test005.java
testcase/src/test/java/stest/tron/wallet/dailybuild/freezeV2/FreezeBalanceV2Test006.java
testcase/src/test/java/stest/tron/wallet/dailybuild/freezeV2/FreezeWeightDeflationV2Test.java
testcase/src/test/java/stest/tron/wallet/dailybuild/http/HttpTestFreezeV2001.java

fix bug,checkstyle,add pbft query
- Unit Tests
**Follow up**

New freeze queryhttp

---

testcase/src/test/java/stest/tron/wallet/dailybuild/freezeV2/FreezeBalanceV2Test002.java

fix a TestCase BUG
- Unit Tests
**Follow up**

fix case BUG

---

testcase/src/test/java/stest/tron/wallet/dailybuild/http/HttpTestAccount002.java

fix case BUG
- Unit Tests
**Follow up**

New freeze

---

testcase/src/test/java/stest/tron/wallet/dailybuild/manual/WalletTestBlock001.java

add grpc headers for some basic cases
- Unit Tests
**Follow up**

add grpc header for some basic cases

---

testcase/src/test/java/stest/tron/wallet/dailybuild/http/HttpRateLimite001.java
testcase/src/test/java/stest/tron/wallet/dailybuild/longexecutiontime/DynamicEnergyTest001.java

add qps case and fix BUG
- Unit Tests
**Follow up**

add qps case and fix BUG

---

testcase/src/test/java/stest/tron/wallet/dailybuild/http/HttpRateLimite001.java

fix case test11GlobalQpsRateForGrpcDifferentPort BUG
- Unit Tests
**Follow up**

fix case test11GlobalQpsRateForGrpcDifferentPort BUG

---

testcase/src/test/java/stest/tron/wallet/common/client/utils/JsonRpcBase.java
testcase/src/test/java/stest/tron/wallet/common/client/utils/PublicMethed.java
testcase/src/test/java/stest/tron/wallet/common/client/utils/ZenTrc20Base.java
testcase/src/test/java/stest/tron/wallet/dailybuild/longexecutiontime/DynamicEnergyTest001.java
testcase/src/test/java/stest/tron/wallet/dailybuild/manual/ContractScenario015.java
testcase/src/test/java/stest/tron/wallet/dailybuild/trctoken/ContractTrcToken014.java
testcase/src/test/java/stest/tron/wallet/dailybuild/tvmnewcommand/create2/Create2Test015.java
testcase/src/test/java/stest/tron/wallet/dailybuild/tvmnewcommand/newGrammar/NewFeatureForSolc086.java

fix case BUG and  replaceConfig BUG
- Unit Tests
**Follow up**

fix case BUG and  replaceConfig BUG

---

testcase/src/test/java/stest/tron/wallet/common/client/utils/PublicMethed.java
testcase/src/test/java/stest/tron/wallet/dailybuild/http/HttpRateLimite001.java
testcase/src/test/java/stest/tron/wallet/dailybuild/manual/ContractScenario011.java

fix case triggerUseTriggerEnergyUsage and delete useless code
- Unit Tests
**Follow up**

fix case triggerUseTriggerEnergyUsage and delete useless code

---

testcase/src/test/java/stest/tron/wallet/common/client/utils/HttpMethed.java
testcase/src/test/java/stest/tron/wallet/common/client/utils/PublicMethed.java
testcase/src/test/java/stest/tron/wallet/dailybuild/http/HttpTestConstantContract001.java
testcase/src/test/java/stest/tron/wallet/dailybuild/http/HttpTestEstimateEnergy.java

add estimateEnergy in common method when deployContract
- Unit Tests
**Follow up**

add estimateEnergy in common method when deployContract

---

testcase/src/test/java/stest/tron/wallet/common/client/utils/ZenTrc20Base.java
testcase/src/test/resources/logback-test.xml

add check proposal in zenTokenBase
- Unit Tests
**Follow up**

add check proposal in zenTokenBase

---

testcase/src/test/java/stest/tron/wallet/common/client/utils/ZenTrc20Base.java

set ZenTrc20Base extend JsonRpcBase
- Unit Tests
**Follow up**

set ZenTrc20Base extend JsonRpcBase

---

testcase/src/test/java/stest/tron/wallet/common/client/utils/ZenTrc20Base.java

fix open proposals BUG
- Unit Tests
**Follow up**

fix open proposals BUG

---

protocol/src/main/protos/api/zkevm.proto
testcase/src/test/java/stest/tron/wallet/common/client/utils/PublicMethodForZkEvm.java
testcase/src/test/resources/testng.conf

add zkEvm proto and zkEvm PublicMethod
- Unit Tests
**Follow up**

add zkEvm proto and zkEvm PublicMethod

---

protocol/src/main/protos/api/zkevm.proto
testcase/src/test/java/stest/tron/wallet/zkevm/FullFlow.java
testcase/src/test/java/stest/tron/wallet/zkevm/ZkEvmBridgeApiTest001.java

add ZkEvmBridgeApiTest001 and modify zkevm.proto
- Unit Tests
**Follow up**

add ZkEvmBridgeApiTest001 and modify zkevm.proto

---

testcase/src/test/java/stest/tron/wallet/dailybuild/assetissue/grammar/ContractGrammar003.java
testcase/src/test/java/stest/tron/wallet/dailybuild/freezeV2/FreezeBalanceV2Test002.java
testcase/src/test/java/stest/tron/wallet/dailybuild/http/HttpShieldTrc20Token002.java
testcase/src/test/java/stest/tron/wallet/dailybuild/http/HttpShieldTrc20Token003.java
testcase/src/test/java/stest/tron/wallet/dailybuild/http/HttpShieldTrc20Token004.java
testcase/src/test/java/stest/tron/wallet/dailybuild/http/HttpShieldTrc20Token005.java
testcase/src/test/java/stest/tron/wallet/dailybuild/http/HttpTestZenToken001.java
testcase/src/test/java/stest/tron/wallet/dailybuild/http/HttpTestZenToken002.java
testcase/src/test/java/stest/tron/wallet/dailybuild/internaltransaction/ContractInternalTransaction003.java
testcase/src/test/java/stest/tron/wallet/dailybuild/longexecutiontime/DynamicEnergyTest001.java
testcase/src/test/java/stest/tron/wallet/dailybuild/manual/RequireException.java
testcase/src/test/java/stest/tron/wallet/dailybuild/multisign/MultiSign23.java
testcase/src/test/java/stest/tron/wallet/dailybuild/multisign/MultiSign24.java
testcase/src/test/java/stest/tron/wallet/dailybuild/operationupdate/MutiSignClearContractAbiTest.java
testcase/src/test/java/stest/tron/wallet/dailybuild/operationupdate/MutiSignMarketAssetTest.java
testcase/src/test/java/stest/tron/wallet/dailybuild/operationupdate/MutiSignUpdataBrokerageTest.java
testcase/src/test/java/stest/tron/wallet/dailybuild/tvmnewcommand/extCodeHash/ExtCodeHashTest007.java
testcase/src/test/java/stest/tron/wallet/dailybuild/zentrc20token/ShieldTrc20Token003.java

delete useless wait block in some case
- Unit Tests
**Follow up**

delete useless wait block in some case

---

testcase/src/test/java/stest/tron/wallet/dailybuild/tvmnewcommand/newGrammar/UsdtTest001.java

add usdt case
- Unit Tests
**Follow up**

add usdt case

---

testcase/src/test/java/stest/tron/wallet/common/client/utils/HttpMethed.java
testcase/src/test/java/stest/tron/wallet/common/client/utils/PublicMethed.java
testcase/src/test/java/stest/tron/wallet/dailybuild/freezeV2/FreezeBalanceV2Test006.java
testcase/src/test/java/stest/tron/wallet/dailybuild/http/HttpTestFreezeV2001.java

1.add case about delegateLockPeriod
- Unit Tests
**Follow up**

add case about delegateLockPeriod

---

testcase/src/test/java/stest/tron/wallet/common/client/utils/ProposalEnum.java
testcase/src/test/java/stest/tron/wallet/common/client/utils/PublicMethed.java
testcase/src/test/java/stest/tron/wallet/dailybuild/freezeV2/FreezeBalanceV2Test006.java
testcase/src/test/java/stest/tron/wallet/dailybuild/http/HttpTestFreezeV2001.java
testcase/src/test/resources/testng.conf

1. add ProposalEnum
2. change case about getMaxDelegateLockPeriod
3. add PublicMethod unDelegateResourceV2AndGetTransactionExtention
4. fix checkStyle
5. change testng.conf proposal getMaxDelegateLockPeriod value to 864000
- Unit Tests
**Follow up**

fix checkStyle and case about getMaxDelegateLockPeriod 

---

testcase/src/test/java/stest/tron/wallet/common/client/utils/TransactionUtils.java

add ContractType to transactionMap
- Unit Tests
**Follow up**

add ContractType to transactionMap

---

testcase/src/test/java/stest/tron/wallet/common/client/utils/DailyBuildReport.java
testcase/src/test/java/stest/tron/wallet/dailybuild/http/HttpTestEasyAccount001.java
testcase/src/test/java/stest/tron/wallet/dailybuild/operationupdate/MutiSignSmartContractTest.java

1.optimize DailyBuildReport class in muti-thread running
2.set case test03ValideteAddress enable=true
3.optimize case testMutiSignForSmartContract
- Unit Tests
**Follow up**

optimize case and fix DailyBuildReport in muti-thread running

---

protocol/src/main/protos/api/api.proto
testcase/src/test/java/stest/tron/wallet/common/client/utils/HttpMethed.java
testcase/src/test/java/stest/tron/wallet/common/client/utils/ProposalEnum.java
testcase/src/test/java/stest/tron/wallet/common/client/utils/PublicMethed.java
testcase/src/test/java/stest/tron/wallet/dailybuild/http/HttpTestResourcePrices.java
testcase/src/test/java/stest/tron/wallet/dailybuild/manual/ResourcePriceTest001.java

Add cases for ResourcePrices API
- Unit Tests
**Follow up**

Add cases for ResourcePrices API

---

testcase/src/test/java/stest/tron/wallet/dailybuild/http/HttpTestResourcePrices.java
testcase/src/test/java/stest/tron/wallet/dailybuild/manual/ResourcePriceTest001.java

fix case bug in resourcePrices
- Unit Tests
**Follow up**

fix case bug in resourcePrices

---

testcase/src/test/java/stest/tron/wallet/dailybuild/http/HttpTestResourcePrices.java
testcase/src/test/java/stest/tron/wallet/dailybuild/manual/ResourcePriceTest001.java

fix case bug and add fullNode's SolidityPort in case
- Unit Tests
**Follow up**

fix case bug and add fullNode's SolidityPort in case

---

testcase/src/test/java/stest/tron/wallet/dailybuild/manual/ResourcePriceTest001.java

fix case bug in ResourcePriceTest001
- Unit Tests
**Follow up**

fix case bug in ResourcePriceTest001

---

testcase/src/test/java/stest/tron/wallet/dailybuild/operationupdate/MutiSignClearContractAbiTest.java

fix case in test1MutiSignForClearContractAbi
- Unit Tests
**Follow up**

fix case in test1MutiSignForClearContractAbi

---

testcase/src/test/java/stest/tron/wallet/dailybuild/eventquery/EventQuery003.java
testcase/src/test/java/stest/tron/wallet/dailybuild/eventquery/EventQuery005.java
testcase/src/test/java/stest/tron/wallet/dailybuild/eventquery/MongoEventQuery005.java
testcase/src/test/java/stest/tron/wallet/dailybuild/tvmnewcommand/transferfailed/TransferFailed003.java

1. Add case about EventQueue new Field in both MongoDB and Native queue
2. fix case in test1TransferTokenEnough and test02EventQueryForContractSolidityEvent
- Unit Tests
**Follow up**

Add case and fix case BUG

---

testcase/src/test/java/stest/tron/wallet/dailybuild/eventquery/EventQuery005.java
testcase/src/test/java/stest/tron/wallet/dailybuild/eventquery/MongoEventQuery005.java

fix case BUG in EventQuery005
- Unit Tests
**Follow up**

fix case BUG in EventQuery005

---

testcase/src/test/java/stest/tron/wallet/dailybuild/eventquery/EventQuery005.java

optimize case test04EventQueryForTransactionUnDelegateResource
- Unit Tests
**Follow up**

optimize case test04EventQueryForTransactionUnDelegateResource

---

testcase/src/test/java/stest/tron/wallet/dailybuild/eventquery/EventQuery005.java

Disable unstable case
- Unit Tests
**Follow up**

Disable unstable case

---

testcase/src/test/java/stest/tron/wallet/dailybuild/tvmnewcommand/transferfailed/TransferFailed004.java
testcase/src/test/java/stest/tron/wallet/dailybuild/tvmnewcommand/transferfailed/TransferFailed008.java

fix unstable case in TransferFailed004 and TransferFailed008
- Unit Tests
**Follow up**

fix unstable case in TransferFailed004 and TransferFailed008

---

testcase/src/test/java/stest/tron/wallet/common/client/utils/JsonRpcBase.java
testcase/src/test/java/stest/tron/wallet/common/client/utils/ProposalEnum.java

fix proposalName error in ProposalEnum
- Unit Tests
**Follow up**

fix proposalName error in ProposalEnum

---

testcase/src/test/java/stest/tron/wallet/common/client/utils/PublicMethed.java
testcase/src/test/java/stest/tron/wallet/dailybuild/grpcurl/GrpcReflectionTest001.java
testcase/src/test/resources/testng.conf

add gRPCurl case
- Unit Tests
**Follow up**

add gRPCurl case

---

build.gradle
protocol/build.gradle
testcase/build.gradle
testcase/src/test/java/stest/tron/wallet/dailybuild/grpcurl/GrpcReflectionTest001.java
testcase/src/test/java/stest/tron/wallet/dailybuild/manual/EstimateEnergyTest001.java

upgrade dependency version
- Unit Tests
**Follow up**

upgrade dependency version
